//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartActivity
    {
        public int Id { get; set; }
        public int CartDeliveryId { get; set; }
        public System.DateTime dtActivity { get; set; }
        public int CartActivityTypeId { get; set; }
    
        public virtual CartDelivery CartDelivery { get; set; }
        public virtual CartActivityType CartActivityType { get; set; }
    }
}
