//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartRelease
    {
        public int Id { get; set; }
        public System.DateTime DtRelease { get; set; }
        public string ReleaseBy { get; set; }
        public string LoginId { get; set; }
        public int CartDetailId { get; set; }
        public int UserDetailId { get; set; }
        public int StorePickupPointId { get; set; }
    
        public virtual CartDetail CartDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual StorePickupPoint StorePickupPoint { get; set; }
    }
}
