//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartDetail()
        {
            this.CartItems = new HashSet<CartItem>();
            this.CartDeliveries = new HashSet<CartDelivery>();
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.RiderCashDetails = new HashSet<RiderCashDetail>();
            this.StoreQueOrders = new HashSet<StoreKioskOrder>();
            this.CartHistories = new HashSet<CartHistory>();
        }
    
        public int Id { get; set; }
        public int UserDetailId { get; set; }
        public int StoreDetailId { get; set; }
        public int CartStatusId { get; set; }
        public System.DateTime DtPickup { get; set; }
        public string DeliveryType { get; set; }
        public int StorePickupPointId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual StoreDetail StoreDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual CartStatus CartStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDelivery> CartDeliveries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiderCashDetail> RiderCashDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreKioskOrder> StoreQueOrders { get; set; }
        public virtual StorePickupPoint StorePickupPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartHistory> CartHistories { get; set; }
    }
}
