//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartHistory
    {
        public int Id { get; set; }
        public int CartStatusId { get; set; }
        public string UserId { get; set; }
        public System.DateTime dtStatus { get; set; }
        public int CartDetailId { get; set; }
    
        public virtual CartStatus CartStatu { get; set; }
        public virtual CartDetail CartDetail { get; set; }
    }
}
