//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecartdbContainer : DbContext
    {
        public ecartdbContainer()
            : base("name=ecartdbContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<StoreDetail> StoreDetails { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
        public virtual DbSet<StoreStatus> StoreStatus { get; set; }
        public virtual DbSet<StoreCategory> StoreCategories { get; set; }
        public virtual DbSet<MasterCity> MasterCities { get; set; }
        public virtual DbSet<MasterArea> MasterAreas { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<ItemMasterCategory> ItemMasterCategories { get; set; }
        public virtual DbSet<StoreItem> StoreItems { get; set; }
        public virtual DbSet<CartDetail> CartDetails { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<CartStatus> CartStatus { get; set; }
        public virtual DbSet<CartHistory> CartHistories { get; set; }
        public virtual DbSet<CartItemStatus> CartItemStatus { get; set; }
        public virtual DbSet<ItemCatGroup> ItemCatGroups { get; set; }
        public virtual DbSet<StorePickupPoint> StorePickupPoints { get; set; }
        public virtual DbSet<StorePickupPartner> StorePickupPartners { get; set; }
        public virtual DbSet<StorePickupStatus> StorePickupStatus { get; set; }
        public virtual DbSet<CartDelivery> CartDeliveries { get; set; }
        public virtual DbSet<RiderDetail> RiderDetails { get; set; }
        public virtual DbSet<RiderStatus> RiderStatus { get; set; }
        public virtual DbSet<CartActivity> CartActivities { get; set; }
        public virtual DbSet<CartActivityType> CartActivityTypes { get; set; }
        public virtual DbSet<StoreImage> StoreImages { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<StoreImgType> StoreImgTypes { get; set; }
        public virtual DbSet<StorePayment> StorePayments { get; set; }
        public virtual DbSet<StorePaymentType> StorePaymentTypes { get; set; }
        public virtual DbSet<StorePaymentStatus> StorePaymentStatus { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
        public virtual DbSet<PaymentReceiver> PaymentReceivers { get; set; }
        public virtual DbSet<PaymentStatus> PaymentStatus { get; set; }
        public virtual DbSet<RiderCashDetail> RiderCashDetails { get; set; }
        public virtual DbSet<RiderCashParty> RiderCashParties { get; set; }
        public virtual DbSet<PaymentParty> PaymentParties { get; set; }
        public virtual DbSet<StoreKiosk> StoreKiosks { get; set; }
        public virtual DbSet<StoreKioskOrder> StoreKioskOrders { get; set; }
    }
}
