//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterCategory
    {
        public int Id { get; set; }
        public int ItemCategoryId { get; set; }
        public int ItemMasterId { get; set; }
    
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
