//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiderCashDetail
    {
        public int Id { get; set; }
        public int RiderDetailId { get; set; }
        public System.DateTime DtCash { get; set; }
        public decimal Amount { get; set; }
        public int RiderCashPartyId { get; set; }
        public int CartDetailId { get; set; }
    
        public virtual RiderDetail RiderDetail { get; set; }
        public virtual RiderCashParty RiderCashParty { get; set; }
        public virtual CartDetail CartDetail { get; set; }
    }
}
