//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreDetail()
        {
            this.StoreItems = new HashSet<StoreItem>();
            this.CartDetails = new HashSet<CartDetail>();
            this.StorePickupPoints = new HashSet<StorePickupPoint>();
            this.StorePickupPartners = new HashSet<StorePickupPartner>();
            this.StoreImages = new HashSet<StoreImage>();
            this.StorePayments = new HashSet<StorePayment>();
            this.StoreQues = new HashSet<StoreKiosk>();
        }
    
        public int Id { get; set; }
        public string LoginId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public int StoreStatusId { get; set; }
        public int StoreCategoryId { get; set; }
        public int MasterCityId { get; set; }
        public int MasterAreaId { get; set; }
    
        public virtual StoreStatus StoreStatu { get; set; }
        public virtual StoreCategory StoreCategory { get; set; }
        public virtual MasterCity MasterCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreItem> StoreItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        public virtual MasterArea MasterArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorePickupPoint> StorePickupPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorePickupPartner> StorePickupPartners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreImage> StoreImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorePayment> StorePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreKiosk> StoreQues { get; set; }
    }
}
