//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreImage
    {
        public int Id { get; set; }
        public int StoreDetailId { get; set; }
        public string ImageUrl { get; set; }
        public int StoreImgTypeId { get; set; }
    
        public virtual StoreDetail StoreDetail { get; set; }
        public virtual StoreImgType StoreImgType { get; set; }
    }
}
