//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePayment
    {
        public int Id { get; set; }
        public int StoreDetailId { get; set; }
        public System.DateTime dtPayment { get; set; }
        public decimal Amount { get; set; }
        public int StorePaymentTypeId { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> dtPosted { get; set; }
        public int StorePaymentStatusId { get; set; }
    
        public virtual StoreDetail StoreDetail { get; set; }
        public virtual StorePaymentType StorePaymentType { get; set; }
        public virtual StorePaymentStatus StorePaymentStatu { get; set; }
    }
}
