//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePickupPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StorePickupPoint()
        {
            this.StorePickupPartners = new HashSet<StorePickupPartner>();
            this.CartDetails = new HashSet<CartDetail>();
            this.CartReleases = new HashSet<CartRelease>();
        }
    
        public int Id { get; set; }
        public int StoreDetailId { get; set; }
        public string Address { get; set; }
        public string Remarks { get; set; }
        public int StorePickupStatusId { get; set; }
    
        public virtual StoreDetail StoreDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StorePickupPartner> StorePickupPartners { get; set; }
        public virtual StorePickupStatus StorePickupStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartRelease> CartReleases { get; set; }
    }
}
