//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCartModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplication
    {
        public int Id { get; set; }
        public System.DateTime DtApplied { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int UserDetailId { get; set; }
        public int UserApplicationStatusId { get; set; }
        public int UserApplicationTypeId { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserApplicationStatus UserApplicationStatu { get; set; }
        public virtual UserApplicationType UserApplicationType { get; set; }
    }
}
